// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOa-5xlm4Ndzg8qtBocl2NdZnSOz-KZ6E',
    appId: '1:728205946627:web:665168c47885e703f78336',
    messagingSenderId: '728205946627',
    projectId: 'chatgva',
    authDomain: 'chatgva.firebaseapp.com',
    storageBucket: 'chatgva.firebasestorage.app',
    measurementId: 'G-DC676EMV97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF43dXUSNNyQooUHiGd9nWni5NBmUfHKc',
    appId: '1:728205946627:android:a6350a54d0faa704f78336',
    messagingSenderId: '728205946627',
    projectId: 'chatgva',
    storageBucket: 'chatgva.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiOl1y6v5MTiMNadnEnVh-ymv8cUZ8Y6I',
    appId: '1:728205946627:ios:acd2296571c4078df78336',
    messagingSenderId: '728205946627',
    projectId: 'chatgva',
    storageBucket: 'chatgva.firebasestorage.app',
    iosBundleId: 'com.iabd.chatgva',
  );
}
